trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      export DEBIAN_FRONTEND="noninteractive"
      sudo debconf-set-selections <<< "mariadb-server mysql-server/root_password password root"
      sudo debconf-set-selections <<< "mariadb-server mysql-server/root_password_again password root"
      sudo apt-get install software-properties-common
      sudo apt install --yes mariadb-server libmysqlclient-dev
      sudo mysql -uroot -proot -e 'drop user if exists test@localhost;'
      sudo mysql  -uroot -proot -e 'create user test@localhost;'
      sudo mysql  -uroot -proot -e 'drop database if exists test;'
      sudo mysql  -uroot -proot -e 'create database test;'
      sudo mysql  -uroot -proot -e 'grant all on *.* to test@localhost;' || true
      echo "DATABASE_URL=mysql://test@localhost/test" > .env
    displayName: Install MariaDB

  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
      export PATH=$PATH:$HOME/.cargo/bin
      rustup default nightly
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust

  - script: |
      rustc -Vv
      cargo -V
    displayName: Query rust and cargo versions

  - script: cargo install diesel_cli --no-default-features --features=mysql
    displayName: Install diesel CLI

  - script: diesel migration run
    displayName: Run migrations

  - script: cargo build --all --release
    displayName: Cargo build release
    
  - script: cargo test --all --release
    displayName: Cargo test release

  - task: CopyFiles@2
    inputs:
      contents: '$(System.DefaultWorkingDirectory)/target/release/records-rust'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy build'
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: records-rust
    displayName: 'Upload artifacts'
